services:
  socket_wrapper:
    class: services.SocketWrapper
  user_entity:
    class: entity.User

  proxy_manager:
    class: services.proxy.ProxyManager
    arguments:
      - parameters.proxy_deep